TEXTS = {
    "uz": {
        "welcome": "Assalomu alaykum! Kerakli bo‘limni tanlang:",
        "posts": "📝 Postlar bo‘limi.\n\nBu yerga postlar havolasi yoki ma'lumotlari yoziladi.",
        "channels": "📢 Kanallar bo‘limi.\n\nBu yerga kanallaringiz ro‘yxatini yozasiz.",
        "about": "ℹ️ About\n\nBu bot sizning shaxsiy/about ma'lumotlaringiz uchun yaratilgan.",
        "services": "🛠 Xizmatlar\n\nBu yerga xizmatlaringiz ro‘yxatini yozasiz.",
        "choose_language": "🌐 Tilni tanlang:",
        "rate_bot": "⭐ Botni baholash uchun 1 dan 5 gacha yuboring.",
        "send_message": "✉️ Menga xabar yuborish uchun xabaringizni yozing.",
        "language_changed_uz": "✅ Til o‘zbek tiliga o‘zgartirildi.",
        "language_changed_ru": "✅ Язык изменён на русский.",
        "language_changed_en": "✅ Language changed to English.",
        "unknown": "Kechirasiz, bu buyruqni tushunmadim.",
        "message_sent": "✅ Xabaringiz adminga yuborildi.",
    },
    "ru": {
        "welcome": "Здравствуйте! Выберите нужный раздел:",
        "posts": "📝 Раздел постов.\n\nСюда добавляется информация о постах.",
        "channels": "📢 Раздел каналов.\n\nСюда добавляется список ваших каналов.",
        "about": "ℹ️ About\n\nЭтот бот создан для вашей личной/about информации.",
        "services": "🛠 Услуги\n\nСюда добавляется список ваших услуг.",
        "choose_language": "🌐 Выберите язык:",
        "rate_bot": "⭐ Оцените бота, отправив число от 1 до 5.",
        "send_message": "✉️ Напишите сообщение, чтобы отправить его админу.",
        "language_changed_uz": "✅ Til o‘zbek tiliga o‘zgartirildi.",
        "language_changed_ru": "✅ Язык изменён на русский.",
        "language_changed_en": "✅ Language changed to English.",
        "unknown": "Извините, я не понял эту команду.",
        "message_sent": "✅ Ваше сообщение отправлено админу.",
    },
    "en": {
        "welcome": "Hello! Choose a section:",
        "posts": "📝 Posts section.\n\nAdd your post information here.",
        "channels": "📢 Channels section.\n\nAdd your channel list here.",
        "about": "ℹ️ About\n\nThis bot is created for your personal/about information.",
        "services": "🛠 Services\n\nAdd your services here.",
        "choose_language": "🌐 Choose a language:",
        "rate_bot": "⭐ Rate the bot by sending a number from 1 to 5.",
        "send_message": "✉️ Write your message to send it to the admin.",
        "language_changed_uz": "✅ Til o‘zbek tiliga o‘zgartirildi.",
        "language_changed_ru": "✅ Язык изменён на русский.",
        "language_changed_en": "✅ Language changed to English.",
        "unknown": "Sorry, I didn't understand that command.",
        "message_sent": "✅ Your message has been sent to the admin.",
    }
}