TEXTS = {
    "uz": {
        "welcome": "👋 Assalomu alaykum.\nKerakli bo‘limni tanlang:",
        "menu_posts": "📰 Postlar",
        "menu_channels": "📢 Kanallar",
        "menu_about": "👤 About",
        "menu_services": "🛠 Xizmatlar",
        "menu_language": "🌐 Tillar",
        "menu_rating": "⭐ Baholash",
        "menu_contact": "✉️ Xabar yuborish",
        "back": "🔙 Ortga",
        "last_posts": "📰 <b>So‘nggi postlar</b>",
        "all_posts_btn": "📚 Barcha postlar",
        "all_posts": "📚 <b>Barcha postlar</b>",
        "no_posts": "📰 Hozircha postlar mavjud emas.",
        "channels_title": "📢 <b>BIZNING SAHIFALAR</b>\n\nKerakli sahifani tanlang:",
        "no_channels": "📢 Hozircha sahifalar qo‘shilmagan.",
        "about_title": "👤 <b>ABOUT</b>",
        "no_about": "Hozircha about matni mavjud emas.",
        "services_title": "🛠 <b>Xizmatlar ro‘yxati</b>",
        "no_services": "🛠 Hozircha xizmatlar qo‘shilmagan.",
        "choose_rating": "⭐ Botni baholang:",
        "choose_language": "🌐 Tilni tanlang:",
        "contact_prompt": "✉️ Xabaringizni yozing.\nBekor qilish uchun '🔙 Ortga' ni bosing.",
        "contact_sent": "✅ Xabaringiz yuborildi.\nTez orada ko‘rib chiqamiz.",
        "cancelled": "🏠 Bekor qilindi.",
        "invalid_rating": "⭐ 1 dan ⭐ 5 gacha tanlang.",
        "language_changed_uz": "🇺🇿 Til o‘zbek tiliga o‘zgartirildi.",
        "language_changed_ru": "🇷🇺 Язык изменён на русский.",
        "language_changed_en": "🇬🇧 Language changed to English.",
        "rating_1": "😔 Afsus, bot sizga yoqmagan ko‘rinadi.\nKamchiliklarni yaxshilash ustida ishlaymiz.",
        "rating_2": "🙏 Rahmat.\nFikringiz biz uchun muhim, xizmat sifatini yaxshilashga harakat qilamiz.",
        "rating_3": "🙂 Rahmat.\nBotni yanada qulay va foydali qilish ustida ishlaymiz.",
        "rating_4": "💙 Katta rahmat.\nBot sizga foydali bo‘layotganidan xursandmiz.",
        "rating_5": "🌟 Juda katta rahmat.\nYuqori bahoyingiz biz uchun juda muhim.",
        "post_not_found": "❌ Post topilmadi.",
        "choose_menu": "Kerakli bo‘limni menyudan tanlang.",
        "instagram_label": "📸 Instagram",
    },
    "ru": {
        "welcome": "👋 Здравствуйте.\nВыберите нужный раздел:",
        "menu_posts": "📰 Посты",
        "menu_channels": "📢 Каналы",
        "menu_about": "👤 About",
        "menu_services": "🛠 Услуги",
        "menu_language": "🌐 Языки",
        "menu_rating": "⭐ Оценка",
        "menu_contact": "✉️ Отправить сообщение",
        "back": "🔙 Назад",
        "last_posts": "📰 <b>Последние посты</b>",
        "all_posts_btn": "📚 Все посты",
        "all_posts": "📚 <b>Все посты</b>",
        "no_posts": "📰 Постов пока нет.",
        "channels_title": "📢 <b>НАШИ СТРАНИЦЫ</b>\n\nВыберите нужную страницу:",
        "no_channels": "📢 Страницы пока не добавлены.",
        "about_title": "👤 <b>ABOUT</b>",
        "no_about": "Текст about пока не добавлен.",
        "services_title": "🛠 <b>Список услуг</b>",
        "no_services": "🛠 Услуги пока не добавлены.",
        "choose_rating": "⭐ Оцените бота:",
        "choose_language": "🌐 Выберите язык:",
        "contact_prompt": "✉️ Напишите ваше сообщение.\nЧтобы отменить, нажмите '🔙 Назад'.",
        "contact_sent": "✅ Ваше сообщение отправлено.\nСкоро мы его рассмотрим.",
        "cancelled": "🏠 Отменено.",
        "invalid_rating": "⭐ Выберите от ⭐ 1 до ⭐ 5.",
        "language_changed_uz": "🇺🇿 Til o‘zbek tiliga o‘zgartirildi.",
        "language_changed_ru": "🇷🇺 Язык изменён на русский.",
        "language_changed_en": "🇬🇧 Language changed to English.",
        "rating_1": "😔 Похоже, бот вам не понравился.\nБудем работать над улучшением.",
        "rating_2": "🙏 Спасибо.\nВаше мнение важно для нас, будем улучшать качество.",
        "rating_3": "🙂 Спасибо.\nБудем делать бота ещё удобнее и полезнее.",
        "rating_4": "💙 Большое спасибо.\nРады, что бот вам полезен.",
        "rating_5": "🌟 Огромное спасибо.\nВаша высокая оценка очень важна для нас.",
        "post_not_found": "❌ Пост не найден.",
        "choose_menu": "Выберите нужный раздел из меню.",
        "instagram_label": "📸 Instagram",
    },
    "en": {
        "welcome": "👋 Hello.\nChoose a section:",
        "menu_posts": "📰 Posts",
        "menu_channels": "📢 Channels",
        "menu_about": "👤 About",
        "menu_services": "🛠 Services",
        "menu_language": "🌐 Languages",
        "menu_rating": "⭐ Rate",
        "menu_contact": "✉️ Send message",
        "back": "🔙 Back",
        "last_posts": "📰 <b>Latest posts</b>",
        "all_posts_btn": "📚 All posts",
        "all_posts": "📚 <b>All posts</b>",
        "no_posts": "📰 No posts yet.",
        "channels_title": "📢 <b>OUR PAGES</b>\n\nChoose a page:",
        "no_channels": "📢 No pages added yet.",
        "about_title": "👤 <b>ABOUT</b>",
        "no_about": "About text is not available yet.",
        "services_title": "🛠 <b>Services list</b>",
        "no_services": "🛠 No services added yet.",
        "choose_rating": "⭐ Rate the bot:",
        "choose_language": "🌐 Choose a language:",
        "contact_prompt": "✉️ Write your message.\nPress '🔙 Back' to cancel.",
        "contact_sent": "✅ Your message has been sent.\nWe will review it soon.",
        "cancelled": "🏠 Cancelled.",
        "invalid_rating": "⭐ Choose from ⭐ 1 to ⭐ 5.",
        "language_changed_uz": "🇺🇿 Til o‘zbek tiliga o‘zgartirildi.",
        "language_changed_ru": "🇷🇺 Язык изменён на русский.",
        "language_changed_en": "🇬🇧 Language changed to English.",
        "rating_1": "😔 Looks like you did not like the bot.\nWe will work on improvements.",
        "rating_2": "🙏 Thank you.\nYour opinion matters, we will improve the quality.",
        "rating_3": "🙂 Thank you.\nWe will make the bot more useful and convenient.",
        "rating_4": "💙 Thank you very much.\nWe are glad the bot is useful to you.",
        "rating_5": "🌟 Huge thanks.\nYour high rating means a lot to us.",
        "post_not_found": "❌ Post not found.",
        "choose_menu": "Choose a section from the menu.",
        "instagram_label": "📸 Instagram",
    }
}